seed: 1337
data:
  dataset: cifar10
  root: "./data"
  pin_memory: false 
  num_workers: 4
  batch_size: 128
  val_split: 0.1   # train: 0.9 * 0.8 = 0.72; val: 0.08; test: 0.2 if you want 80/10/10, set splits below
  splits: {train: 0.8, val: 0.1, test: 0.1}
  aug:
    random_crop: true
    random_hflip: true
    normalize: true
train:
  epochs: 50
  optimizer: adam
  lr: 0.001
  weight_decay: 0.0
  device: "cpu"   # "cuda"|"cpu"
  save_best: true
  amp: false # torch.cuda.amp
metrics:
  topk: [1]
  per_class: true
  confusion: true
logging:
  out_dir: "./experiments"
  run_name: null   # auto-filled: {model}-{timestamp}
