defaults_from: "configs/base.yaml"
model:
  name: "cnn"
  blocks:
    - {out_channels: 32, kernel_size: 3, pool: true, bn: true, dropout: 0.0}
    - {out_channels: 64, kernel_size: 3, pool: true, bn: true, dropout: 0.0}
    - {out_channels: 128, kernel_size: 3, pool: true, bn: true, dropout: 0.5}
  fc: [128]
  num_classes: 10
